### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by semisight** [ZukoAnalytics/gtm-template-activity#4]
https://github.com/ZukoAnalytics/gtm-template-activity/blob/a8ad644c415dcc35fc743df0a75f057d12cb607d/template.tpl#L93

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by JoeNyland** [comment]
Hey @semisight Thanks for taking a look at our template. I'll make the proposed changes as soon as possible.

**Comment by semisight** [comment]
Hi Joe,

Could you update the metadata.yaml file to point to the newest/fixed commit? Then we can merge your template.

**Comment by JoeNyland** [comment]
Sure, will do!

**Comment by JoeNyland** [comment]
That's been completed now. Thanks @semisight 🙂

**Comment by kgodsmark** [comment]
@semisight please let us know if this template could now be merged. Thanks so much.
